# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170310_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
